from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EntranceWindow(object):
    def setupUi(self, EntranceWindow):
        EntranceWindow.setObjectName("EntranceWindow")
        EntranceWindow.setEnabled(True)
        EntranceWindow.resize(371, 424)
        EntranceWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(parent=EntranceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Name_game = QtWidgets.QLabel(parent=self.centralwidget)
        self.Name_game.setGeometry(QtCore.QRect(130, 0, 91, 31))
        self.Name_game.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Name_game.setFont(font)
        self.Name_game.setObjectName("Name_game")
        self.label_login = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_login.setGeometry(QtCore.QRect(10, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_login.setFont(font)
        self.label_login.setObjectName("label_login")
        self.login_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.login_input.setGeometry(QtCore.QRect(10, 90, 191, 21))
        self.login_input.setObjectName("login_input")
        self.label_password = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(10, 120, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.password_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(10, 150, 191, 21))
        self.password_input.setObjectName("password_input")
        self.error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(10, 190, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("color: red;")
        self.error_label.setObjectName("error_label")
        self.cancel_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_btn.setGeometry(QtCore.QRect(60, 250, 101, 31))
        self.cancel_btn.setObjectName("cancel_btn")
        self.create_account_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_account_btn.setGeometry(QtCore.QRect(180, 250, 101, 31))
        self.create_account_btn.setObjectName("create_account_btn")
        EntranceWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=EntranceWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 21))
        self.menubar.setObjectName("menubar")
        EntranceWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=EntranceWindow)
        self.statusbar.setObjectName("statusbar")
        EntranceWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EntranceWindow)
        QtCore.QMetaObject.connectSlotsByName(EntranceWindow)

    def retranslateUi(self, EntranceWindow):
        _translate = QtCore.QCoreApplication.translate
        EntranceWindow.setWindowTitle(_translate("EntranceWindow", "MainWindow"))
        self.Name_game.setText(_translate("EntranceWindow", "ВХОД"))
        self.label_login.setText(_translate("EntranceWindow", "Логин:"))
        self.label_password.setText(_translate("EntranceWindow", "Пароль:"))
        self.error_label.setText(_translate("EntranceWindow", "Неверный логин/пароль"))
        self.cancel_btn.setText(_translate("EntranceWindow", "НАЗАД"))
        self.create_account_btn.setText(_translate("EntranceWindow", "ВОЙТИ"))
