from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainMenuWindow(object):
    def setupUi(self, MainMenuWindow):
        MainMenuWindow.setObjectName("MainMenuWindow")
        MainMenuWindow.setEnabled(True)
        MainMenuWindow.resize(1163, 800)
        MainMenuWindow.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainMenuWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainMenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(370, 40, 401, 71))
        self.title_label.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.play_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(370, 220, 421, 71))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(48)
        font.setItalic(False)
        self.play_btn.setFont(font)
        self.play_btn.setObjectName("play_btn")
        self.shop_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.shop_btn.setGeometry(QtCore.QRect(370, 320, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.shop_btn.setFont(font)
        self.shop_btn.setObjectName("shop_btn")
        self.profile_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.profile_btn.setGeometry(QtCore.QRect(370, 430, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.profile_btn.setFont(font)
        self.profile_btn.setObjectName("profile_btn")
        self.exit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(370, 530, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.exit_btn.setFont(font)
        self.exit_btn.setObjectName("exit_btn")
        self.player_info_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.player_info_label.setGeometry(QtCore.QRect(30, 130, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.player_info_label.setFont(font)
        self.player_info_label.setObjectName("player_info_label")
        MainMenuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainMenuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1163, 21))
        self.menubar.setObjectName("menubar")
        MainMenuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainMenuWindow)
        self.statusbar.setObjectName("statusbar")
        MainMenuWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainMenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MainMenuWindow)

    def retranslateUi(self, MainMenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MainMenuWindow.setWindowTitle(_translate("MainMenuWindow", "MainWindow"))
        self.title_label.setText(_translate("MainMenuWindow", "Boss Rush"))
        self.play_btn.setText(_translate("MainMenuWindow", "Играть"))
        self.shop_btn.setText(_translate("MainMenuWindow", "Магазин"))
        self.profile_btn.setText(_translate("MainMenuWindow", "Профиль"))
        self.exit_btn.setText(_translate("MainMenuWindow", "Выход"))
        self.player_info_label.setText(_translate("MainMenuWindow", "Игрок:"))
