from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.setEnabled(True)
        RegisterWindow.resize(371, 424)
        RegisterWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(parent=RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Name_game = QtWidgets.QLabel(parent=self.centralwidget)
        self.Name_game.setGeometry(QtCore.QRect(60, 0, 221, 31))
        self.Name_game.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Name_game.setFont(font)
        self.Name_game.setObjectName("Name_game")
        self.label_login = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_login.setGeometry(QtCore.QRect(10, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_login.setFont(font)
        self.label_login.setObjectName("label_login")
        self.login_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.login_input.setGeometry(QtCore.QRect(10, 90, 191, 21))
        self.login_input.setObjectName("login_input")
        self.label_password = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(10, 120, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.password_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(10, 150, 191, 21))
        self.password_input.setObjectName("password_input")
        self.label_pasword = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_pasword.setGeometry(QtCore.QRect(10, 180, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_pasword.setFont(font)
        self.label_pasword.setObjectName("label_pasword")
        self.confirm_password_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.confirm_password_input.setGeometry(QtCore.QRect(10, 210, 191, 21))
        self.confirm_password_input.setObjectName("confirm_password_input")
        self.error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(10, 250, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("color: red;")
        self.error_label.setObjectName("error_label")
        self.cancel_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_btn.setGeometry(QtCore.QRect(50, 340, 101, 31))
        self.cancel_btn.setObjectName("cancel_btn")
        self.create_account_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_account_btn.setGeometry(QtCore.QRect(180, 340, 101, 31))
        self.create_account_btn.setObjectName("create_account_btn")
        RegisterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=RegisterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 21))
        self.menubar.setObjectName("menubar")
        RegisterWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=RegisterWindow)
        self.statusbar.setObjectName("statusbar")
        RegisterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "MainWindow"))
        self.Name_game.setText(_translate("RegisterWindow", "РЕГИСТРАЦИЯ"))
        self.label_login.setText(_translate("RegisterWindow", "Логин:"))
        self.label_password.setText(_translate("RegisterWindow", "Пароль:"))
        self.label_pasword.setText(_translate("RegisterWindow", "Подтвердите пароль:"))
        self.error_label.setText(_translate("RegisterWindow", "Пароли не совпадают"))
        self.cancel_btn.setText(_translate("RegisterWindow", "НАЗАД"))
        self.create_account_btn.setText(_translate("RegisterWindow", "СОЗДАТЬ"))
